---
- hosts: jenkins
  remote_user: ubuntu
  become: yes
  tasks:

  - name: Ensure jenkins directory on docker host
    file:
      state: directory
      owner: 1000
      group: 1000
      path: /share/jenkins

  - name: Deploy Jenkins container
    command: docker run -d -p 8080:8080 -p 50000:50000 -v /share/jenkins:/var/jenkins_home --name jenkins jenkins/jenkins:lts
